server:
  port: 8080
  error:
    include-exception: true
  shutdown: graceful

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://db-users:5432/users
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  mvc:
    problemdetails:
      enabled: false

api:
  user-service: http://user-service:8080/api/v1/users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  metrics:
    export:
      otlp:
        enabled: false