apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-orders-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-orders
  namespace: default
  labels:
    app: db-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-orders
  template:
    metadata:
      labels:
        app: db-orders
    spec:
      containers:
      - name: db-orders
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "orders"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-orders-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: db-orders-storage
        persistentVolumeClaim:
          claimName: db-orders-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-orders-service
  namespace: default
spec:
  selector:
    app: db-orders
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
