server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: eureka-service
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
